version: "3.5"
services:
  lerAudio:
    image: whats3
    restart: always
    environment:
       - OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       - PATH_MP3=/mp3
       - PATH_SESSION=/session
       - USER_PHONE=5511999988888
    volumes:
       - session:/session
       - mp3:/mp3
volumes:
  session:
    driver: local
    driver_opts:
      type: none
      device: /full/path/to/whatsaudio/mp3
      o: bind
  mp3:
    driver: local
    driver_opts:
      type: none
      device: /full/path/to//whatsaudio/mp3
      o: bind
